name: QUAR
version: '0.1'
summary: QUAR cryptocurrency wallet
description: |
  QUAR is a fully decentralised cryptocurrency built on the premise of providing anonymity, speed, fair mining by being ASIC-resistant and reliability by the usage of Masternodes.
icon: snap/gui/QUAR-qt.png
grade: stable
confinement: strict

apps:
  QUAR-cli:
    command: bin/QUAR-cli
    plugs:
      - network

  QUARd:
    command: bin/QUARd
    plugs:
      - network
      - network-bind

  QUAR-tx:
    command: bin/QUAR-tx
    plugs:
      - network

  QUAR-qt:
    command: desktop-launch $SNAP/bin/QUAR-qt
    desktop: QUAR-qt.desktop
    plugs:
      - desktop
      - home
      - network
      - network-bind
      - x11

parts:
  ppa:
    plugin: nil
    override-pull: |
      add-apt-repository -yu ppa:bitcoin/bitcoin
      apt install -y libdb4.8-dev libdb4.8++-dev
    build-packages:
      - software-properties-common
  QUAR:
    plugin: autotools
    after:
      - ppa
      - desktop-qt5
    source: https://github.com/QUARCore/QUAR.git
    source-depth: 1
    configflags: [--disable-tests, --disable-bench]
    override-build: |
      snapcraftctl build
      cp contrib/debian/QUAR-qt.desktop.desktop $SNAPCRAFT_PART_INSTALL/QUAR-qt.desktop
      sed -i -e 's/Icon=QUAR128/Icon=${SNAP}\/meta\/gui\/QUAR-qt.png/; s/QUAR-qt.desktop/QUAR Core/' $SNAPCRAFT_PART_INSTALL/QUAR-qt.desktop
    build-packages:
      - bsdmainutils
      - libboost-chrono-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-test-dev
      - libboost-thread-dev
      - libevent-dev
      - libminiupnpc-dev
      - libprotobuf-dev
      - libqrencode-dev
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libssl-dev
      - libzmq3-dev
      - pkg-config
      - protobuf-compiler
      - qttools5-dev
      - qttools5-dev-tools
    stage-packages:
      - libatk-adaptor
      - libboost-chrono1.58.0
      - libboost-program-options1.58.0
      - libboost-thread1.58.0
      - libcanberra-gtk-module
      - libcanberra-gtk3-module
      - libdb4.8
      - libdb4.8++
      - libevent-2.0-5
      - libevent-pthreads-2.0-5
      - libgail-common
      - libminiupnpc10
      - libprotobuf9v5
      - libqrencode3
      - libzmq5
